import { Grid, HomeIcon, Settings, Trash, User2Icon } from "lucide-react";

export const data = {
  user: {
    name: "Shadcn",
    email: "sggtmm@gmail.com",
    avatar: User2Icon,
  },
  navMain: [
    {
      title: "Home",
      url: "/dashboard",
      icon: HomeIcon,
    },
    {
      title: "Template",
      url: "/template",
      icon: Grid,
    },
    {
      title: "Trash",
      url: "/trash",
      icon: Trash,
    },
    {
      title: "Setting",
      url: "/setting",
      icon: Settings,
    },
  ],
};

export const containerVariations = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

export const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transistion: {
      type: "spring",
      stiffness: 100,
    },
  },
};

export const themes = [
  {
    name: "Arctic Frost",
    fontFamily: "'Quicksand', sans-serif",
    fontColor: "#2c3e50",
    backgroundColor: "#e0f7fa",
    slideBackgroundColor: "#ffffff",
    accentColor: "#00bcd4",
    gradientBackground: "linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 100%)",
    navbarColor: "#b2ebf2",
    sidebarColor: "#e0f7fa",
    type: "light",
  },
  {
    name: "Sunset Glow",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#2c2c2c",
    backgroundColor: "#fff8e1",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ff8a65",
    gradientBackground: "linear-gradient(135deg, #ffe0b2 0%, #ffccbc 100%)",
    navbarColor: "#ffccbc",
    sidebarColor: "#ffe0b2",
    type: "light",
  },
  {
    name: "Ocean Deep",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#e0f7fa",
    backgroundColor: "#003f5c",
    slideBackgroundColor: "#2f4b7c",
    accentColor: "#00bcd4",
    gradientBackground: "linear-gradient(135deg, #003f5c 0%, #2f4b7c 100%)",
    navbarColor: "#2f4b7c",
    sidebarColor: "#003f5c",
    type: "dark",
  },
  {
    name: "Lavender Sky",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#4a148c",
    backgroundColor: "#f3e5f5",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ce93d8",
    gradientBackground: "linear-gradient(135deg, #f3e5f5 0%, #e1bee7 100%)",
    navbarColor: "#e1bee7",
    sidebarColor: "#f3e5f5",
    type: "light",
  },
  {
    name: "Solar Flare",
    fontFamily: "'Ubuntu', sans-serif",
    fontColor: "#212121",
    backgroundColor: "#fff3e0",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ff7043",
    gradientBackground: "linear-gradient(135deg, #fff3e0 0%, #ffccbc 100%)",
    navbarColor: "#ffccbc",
    sidebarColor: "#fff3e0",
    type: "light",
  },
  {
    name: "Midnight Mist",
    fontFamily: "'Roboto Slab', serif",
    fontColor: "#f5f5f5",
    backgroundColor: "#1a237e",
    slideBackgroundColor: "#283593",
    accentColor: "#7986cb",
    gradientBackground: "linear-gradient(135deg, #1a237e 0%, #283593 100%)",
    navbarColor: "#283593",
    sidebarColor: "#1a237e",
    type: "dark",
  },
  {
    name: "Mint Breeze",
    fontFamily: "'Lato', sans-serif",
    fontColor: "#2e7d32",
    backgroundColor: "#e8f5e9",
    slideBackgroundColor: "#ffffff",
    accentColor: "#66bb6a",
    gradientBackground: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
    navbarColor: "#c8e6c9",
    sidebarColor: "#e8f5e9",
    type: "light",
  },
  {
    name: "Crimson Night",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#ffffff",
    backgroundColor: "#880e4f",
    slideBackgroundColor: "#ad1457",
    accentColor: "#f06292",
    gradientBackground: "linear-gradient(135deg, #880e4f 0%, #ad1457 100%)",
    navbarColor: "#ad1457",
    sidebarColor: "#880e4f",
    type: "dark",
  },
  {
    name: "Golden Hour",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#4e342e",
    backgroundColor: "#fffde7",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ffd54f",
    gradientBackground: "linear-gradient(135deg, #fffde7 0%, #fff9c4 100%)",
    navbarColor: "#fff9c4",
    sidebarColor: "#fffde7",
    type: "light",
  },
  {
    name: "Neon Pulse",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f2027",
    slideBackgroundColor: "#203a43",
    accentColor: "#00f5d4",
    gradientBackground: "linear-gradient(135deg, #0f2027 0%, #203a43 100%)",
    navbarColor: "#203a43",
    sidebarColor: "#0f2027",
    type: "dark",
  },
  {
    name: "Sakura Bloom",
    fontFamily: "'Merriweather', serif",
    fontColor: "#880e4f",
    backgroundColor: "#fce4ec",
    slideBackgroundColor: "#ffffff",
    accentColor: "#f48fb1",
    gradientBackground: "linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)",
    navbarColor: "#f8bbd0",
    sidebarColor: "#fce4ec",
    type: "light",
  },
  {
    name: "Space Dust",
    fontFamily: "'Courier Prime', monospace",
    fontColor: "#cfd8dc",
    backgroundColor: "#263238",
    slideBackgroundColor: "#37474f",
    accentColor: "#80deea",
    gradientBackground: "linear-gradient(135deg, #263238 0%, #37474f 100%)",
    navbarColor: "#37474f",
    sidebarColor: "#263238",
    type: "dark",
  },
  {
    name: "Peach Cream",
    fontFamily: "'Open Sans', sans-serif",
    fontColor: "#6d4c41",
    backgroundColor: "#ffe0b2",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ffab91",
    gradientBackground: "linear-gradient(135deg, #ffe0b2 0%, #ffccbc 100%)",
    navbarColor: "#ffccbc",
    sidebarColor: "#ffe0b2",
    type: "light",
  },
  {
    name: "Cyber Wave",
    fontFamily: "'Share Tech Mono', monospace",
    fontColor: "#00e5ff",
    backgroundColor: "#212121",
    slideBackgroundColor: "#424242",
    accentColor: "#69f0ae",
    gradientBackground: "linear-gradient(135deg, #212121 0%, #424242 100%)",
    navbarColor: "#424242",
    sidebarColor: "#212121",
    type: "dark",
  },
  {
    name: "Emerald Coast",
    fontFamily: "'Cabin', sans-serif",
    fontColor: "#004d40",
    backgroundColor: "#e0f2f1",
    slideBackgroundColor: "#ffffff",
    accentColor: "#4db6ac",
    gradientBackground: "linear-gradient(135deg, #e0f2f1 0%, #b2dfdb 100%)",
    navbarColor: "#b2dfdb",
    sidebarColor: "#e0f2f1",
    type: "light",
  },
  {
    name: "Indigo Realm",
    fontFamily: "'Bitter', serif",
    fontColor: "#ede7f6",
    backgroundColor: "#311b92",
    slideBackgroundColor: "#4527a0",
    accentColor: "#9575cd",
    gradientBackground: "linear-gradient(135deg, #311b92 0%, #4527a0 100%)",
    navbarColor: "#4527a0",
    sidebarColor: "#311b92",
    type: "dark",
  },
  {
    name: "Blush Pink",
    fontFamily: "'Comfortaa', cursive",
    fontColor: "#6a1b9a",
    backgroundColor: "#f8bbd0",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ba68c8",
    gradientBackground: "linear-gradient(135deg, #f8bbd0 0%, #e1bee7 100%)",
    navbarColor: "#e1bee7",
    sidebarColor: "#f8bbd0",
    type: "light",
  },
  {
    name: "Slate Storm",
    fontFamily: "'Source Code Pro', monospace",
    fontColor: "#eceff1",
    backgroundColor: "#37474f",
    slideBackgroundColor: "#455a64",
    accentColor: "#90a4ae",
    gradientBackground: "linear-gradient(135deg, #37474f 0%, #455a64 100%)",
    navbarColor: "#455a64",
    sidebarColor: "#37474f",
    type: "dark",
  },
  {
    name: "Coral Candy",
    fontFamily: "'Rubik', sans-serif",
    fontColor: "#4e342e",
    backgroundColor: "#fbe9e7",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ffab91",
    gradientBackground: "linear-gradient(135deg, #fbe9e7 0%, #ffccbc 100%)",
    navbarColor: "#ffccbc",
    sidebarColor: "#fbe9e7",
    type: "light",
  },
  {
    name: "Charcoal Ember",
    fontFamily: "'Fira Code', monospace",
    fontColor: "#eceff1",
    backgroundColor: "#212121",
    slideBackgroundColor: "#333333",
    accentColor: "#ff7043",
    gradientBackground: "linear-gradient(135deg, #212121 0%, #333333 100%)",
    navbarColor: "#333333",
    sidebarColor: "#212121",
    type: "dark",
  },
];
